name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Preparar el entorno (Python 3.14)
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: pip

      - name: Instalar las dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar las pruebas automáticas
        run: pytest -v
